name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
           serviceAccountJson: ${{ SERVICE_ACCOUNT_JSON }}
           packageName: com.example.MyApp
           releaseFile: ${{ SIGNED_RELEASE_FILE}}
           track: beta
           userFraction: 0.33
    - name: Build with Gradle
      run: ./gradlew build
